name: flex_yemen
description: A fresh start for Flex Yemen Ultimate.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  carousel_slider: ^5.0.0

flutter:
  uses-material-design: true
